name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  build_runner: ^2.11.1
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.10.0
  json_serializable: ^6.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
